### ISSUE TITLE
Site Options item appearing twice in Admin Dashboard Menu

### ISSUE THREAD

**Issue by mikeyrayvon** [interglobalvision/ruberta-la#1]
![screen shot 2017-08-14 at 2 17 15 pm](https://user-images.githubusercontent.com/7727722/29287502-4b29eefa-80fb-11e7-8628-8c0c545789cb.png)

**Comment by mikeyrayvon** [comment]
probably also in the starter pack

**Comment by mikeyrayvon** [comment]
i'm guessing this is due to some change in CMB2

**Comment by mikeyrayvon** [comment]
mm doesn't seem to be the case. just looked thru their recent merged PRs

**Comment by varffs** [comment]
Thought this was a bug in formos-io but must be a new starter pack bug

**Comment by mikeyrayvon** [comment]
doesn't break anything so not super urgent. but still

**Comment by mixcas** [comment]
I checked and is a CMB2 issue. Should i rise and issue on their repo?

**Comment by varffs** [comment]
I dont think so as it isn't core code that is a snippet that is linked to in their wiki (which needs updating anyhow)

**Comment by mixcas** [comment]
I checked, not just randomly guessed. 

CMB2 2.2.5 introduces the bug. Downgrading to 2.2.4 fixes it:

`composer require webdevstudios/cmb2:2.2.4`

**Comment by mixcas** [comment]
you say that the snippet is just outdated? I'll check that

**Comment by mixcas** [comment]
The page about it is blank

So I'm guessing they are updating it? 

https://github.com/CMB2/CMB2/wiki/Using-CMB-to-create-an-Admin-Theme-Options-Page

**Comment by mixcas** [comment]
This one is supposed to be up to date:

https://github.com/CMB2/CMB2/blob/v2.2.5/example-functions.php#L640-L683

**Comment by mixcas** [comment]
Ahhhh

> Options pages are now first-class CMB2 citizens, and registering a box to show on an options page will automatically register the menu page and output the form on the page. See example. (The snippets in the snippet library will be updated to reflect this change)

https://github.com/CMB2/CMB2/releases/tag/v2.2.5

**Comment by varffs** [comment]
Thats very nice. We just need to refactor the starter pack then (and can scrap some of that old snippet library code too) We should rewrite the options page in this project and formos-io and then pull that new code back into the starter
